<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'hero_create' => [['name'], ['_controller' => 'App\\Controller\\HeroController::createHero'], [], [['variable', '/', '[^/]++', 'name', true], ['text', '/api/heroes/create']], [], []],
    'heroes_get' => [[], ['_controller' => 'App\\Controller\\HeroController::getAllHeroes'], [], [['text', '/api/heroes']], [], []],
    'hero_get' => [['id'], ['_controller' => 'App\\Controller\\HeroController::getHeroById'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/heroes']], [], []],
    'hero_update' => [['id', 'newName'], ['_controller' => 'App\\Controller\\HeroController::updateHero'], [], [['variable', '/', '[^/]++', 'newName', true], ['variable', '/', '[^/]++', 'id', true], ['text', '/api/heroes/update']], [], []],
    'hero_delete' => [['id'], ['_controller' => 'App\\Controller\\HeroController::deleteHeroById'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/heroes/delete']], [], []],
    'startup' => [[], ['_controller' => 'App\\Controller\\StartupController::index'], [], [['text', '/']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\StartupController::index'], [], [['text', '/']], [], []],
];
