<?php

namespace ContainerXZWnAmE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHeroService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.QnJslfU.App\Entity\Hero' shared service.
     *
     * @return \App\Entity\Hero
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.QnJslfU": it references class "App\\Entity\\Hero" but no such service exists.');
    }
}
